language: cpp
os: linux
dist: trusty
sudo: required
compiler: clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-3.9
    packages:
      - clang-3.9
      - g++-6
      - libc++-dev
      - ninja-build
      - cmake
      - cmake-data
env:
  global:
    - CC='clang-3.9'
    - CXX='clang++-3.9'
  matrix:
    - TARGET=avx2
    - TARGET=sse42
    - TARGET=learn
    - TARGET=learn-sse42

before_install:
  - env
  - cat /proc/cpuinfo
  - export SRC_DIR="`pwd`/yomita/yomita/src"
script:
  - pwd
  - echo $TARGET
  - mkdir "$TRAVIS_BUILD_DIR/build-ninja-$TARGET"
  - cd "$TRAVIS_BUILD_DIR/build-ninja-$TARGET"
  - cmake -Dtarget=$TARGET -G Ninja "$SRC_DIR" && ninja -v
  - 'if [ "$TARGET" = "avx2" ]; then wget https://github.com/TukamotoRyuzo/Yomita/releases/download/SDT5/yomitaSDT5.zip && unzip yomitaSDT5.zip && mv Yomita-by-clang yomita_engine && cd yomita_engine && echo usi | ./Yomita-by-clang && echo b | ./Yomita-by-clang; fi'
  - 'if [ "$TARGET" = "sse42" ]; then wget https://github.com/TukamotoRyuzo/Yomita/releases/download/SDT5/yomitaSDT5.zip && unzip yomitaSDT5.zip && mv Yomita-by-clang yomita_engine && cd yomita_engine && echo usi | ./Yomita-by-clang && echo b | ./Yomita-by-clang; fi'
  - 'if [ "$TARGET" = "learn" ]; then wget https://github.com/TukamotoRyuzo/Yomita/releases/download/SDT5/yomitaSDT5.zip && unzip yomitaSDT5.zip && mv Yomita-by-clang yomita_engine && cd yomita_engine && echo usi | ./Yomita-by-clang && echo b | ./Yomita-by-clang; fi'
  - 'if [ "$TARGET" = "learn-sse42" ]; then wget https://github.com/TukamotoRyuzo/Yomita/releases/download/SDT5/yomitaSDT5.zip && unzip yomitaSDT5.zip && mv Yomita-by-clang yomita_engine && cd yomita_engine && echo usi | ./Yomita-by-clang && echo b | ./Yomita-by-clang; fi'
# - 'if [ -f "Yomita-by-clang" && "$TARGET" = "avx2" ]; then
